vpc_cidr           = "10.0.0.0/16"
priv_subnet_cidr   = ["10.0.1.0/24", "10.0.2.0/24"]
pub_subnet_cidr    = ["10.0.3.0/24", "10.0.4.0/24"]
subnet_az          = ["us-east-1a", "us-east-1b"]
priv_subnet_name   = "private"
pub_subnet_name    = "public"
region             = "us-east-1"
access_key         = ""
secret_key         = ""
db_username        = "dbuser"
db_password        = ""
db_instance_class  = ""
